dependencies:
  - any: ['package*.json', '.github/dependabot.yml']

workflows:
  - any: ['.github/workflows/**']

ssr:
  - any: ['src/server.ts', 'src/main.server.ts']

tests:
  - any: ['**/*.spec.ts']

documentation:
  - any: ['docs/**', 'README.md', 'SECURITY.md', 'CODE_OF_CONDUCT.md']

config:
  - any: ['angular.json', 'tsconfig*.json', '.prettierrc', 'postcss.config.json']
