dependencies:
  - package*.json
  - .github/dependabot.yml

workflows:
  - .github/workflows/**

ssr:
  - src/server.ts
  - src/main.server.ts

tests:
  - '**/*.spec.ts'

documentation:
  - docs/**
  - README.md
  - SECURITY.md
  - CODE_OF_CONDUCT.md

config:
  - angular.json
  - tsconfig*.json
  - .prettierrc
  - postcss.config.json
