import {
  LucideActivity,
  LucideArrowDown,
  LucideArrowUpRight,
  LucideBot,
  LucideBrainCircuit,
  LucideCheck,
  LucideCircleCheck,
  LucideCompass,
  LucideDatabaseZap,
  LucideLockKeyhole,
  LucideMenu,
  LucideNetwork,
  LucideShieldCheck,
  LucideSparkles,
  LucideSun,
  LucideWaypoints,
  LucideX,
  LucideZap,
  LucideMoon,
} from '@lucide/angular';

export const SAQR_ICONS = [
  LucideActivity,
  LucideArrowDown,
  LucideArrowUpRight,
  LucideBot,
  LucideBrainCircuit,
  LucideCheck,
  LucideCircleCheck,
  LucideCompass,
  LucideDatabaseZap,
  LucideLockKeyhole,
  LucideMenu,
  LucideNetwork,
  LucideShieldCheck,
  LucideSparkles,
  LucideSun,
  LucideWaypoints,
  LucideX,
  LucideZap,
  LucideMoon,
] as const;